# Generated by Django 5.2.4 on 2025-07-17 20:00

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MediaDirectory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text="Nome descritivo deste diretório (ex: 'Filmes', 'Gravações_2025', etc.)", max_length=255)),
                ('path', models.CharField(help_text='Caminho absoluto no sistema de arquivos', max_length=1024, unique=True)),
                ('recursive', models.BooleanField(default=True, help_text='Se True, busca também em subpastas')),
                ('last_scanned', models.DateTimeField(blank=True, help_text='Data/hora da última varredura', null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Video',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('file_name', models.CharField(help_text="Nome do arquivo, ex: 'video_exemplo.mp4'", max_length=255)),
                ('hash', models.CharField(blank=True, max_length=32, null=True)),
                ('title', models.CharField(blank=True, help_text='Título extraído ou definido manualmente', max_length=200, null=True)),
                ('description', models.TextField(blank=True, help_text='Descrição ou anotação opcional')),
                ('path', models.CharField(blank=True, max_length=256, null=True)),
                ('duration', models.FloatField(default=0, help_text='Duração em segundos')),
                ('width', models.PositiveIntegerField(blank=True, help_text='Largura em pixels', null=True)),
                ('height', models.PositiveIntegerField(blank=True, help_text='Altura em pixels', null=True)),
                ('format', models.CharField(blank=True, help_text='Formato contêiner (mp4, mkv, avi, etc.)', max_length=50)),
                ('codec', models.CharField(blank=True, help_text='Codec de vídeo (h264, h265, vp9, etc.)', max_length=50)),
                ('size', models.BigIntegerField(default=0, help_text='Tamanho do arquivo em bytes')),
                ('thumbnail', models.ImageField(blank=True, null=True, upload_to='thumbnails/%Y/%m/%d/')),
                ('file_created', models.DateTimeField(default=django.utils.timezone.now, help_text='Data de criação do arquivo no disco')),
                ('scanned_at', models.DateTimeField(auto_now=True, help_text='Quando esses metadados foram atualizados')),
                ('directory', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='videos', to='data.mediadirectory')),
            ],
            options={
                'ordering': ['-scanned_at', 'file_name'],
            },
        ),
    ]
